server.port=8085
spring.application.name=autoescola_n321

# MySQL
spring.datasource.url=jdbc:mysql://localhost/dbnautoescolan321
spring.datasource.username=${DBN_USER}
spring.datasource.password=${DBN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver