server.port=8085
spring.application.name=autoescola_n321
#spring.jackson.property-naming-strategy=SNAKE_CASE

# MySQL
spring.datasource.url=${DBN_URL}
spring.datasource.username=${DBN_USER}
spring.datasource.password=${DBN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET}